---
name: Build and Push Python Image to Google Cloud Platform
on:
  push:
    branches: [ main ]
jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: checkoutservice
      PROJECT_ID: devops-00000
      ARTIFACT_REG: asia-southeast1-docker.pkg.dev
      IMAGE_REPO: micro
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: google-github-actions/setup-gcloud@v0
      with:
        service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        project_id: ${{ env.PROJECT_ID }}
        export_default_credentials: true

    - name: Build Docker Image
      run: docker build -t $IMAGE_NAME:latest .

    - name: Configure Docker Client
      run: |-
        gcloud auth configure-docker ${ARTIFACT_REG} --quiet

    - name: Push Docker Image to Artifact Registry
      env:
        GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
      run: |-
        docker tag $IMAGE_NAME:latest ${ARTIFACT_REG}/${PROJECT_ID}/${IMAGE_REPO}/$IMAGE_NAME:latest
        docker tag $IMAGE_NAME:latest ${ARTIFACT_REG}/${PROJECT_ID}/${IMAGE_REPO}/$IMAGE_NAME:$GITHUB_RUN_NUMBER
        docker push ${ARTIFACT_REG}/${PROJECT_ID}/${IMAGE_REPO}/$IMAGE_NAME:latest
        docker push ${ARTIFACT_REG}/${PROJECT_ID}/${IMAGE_REPO}/$IMAGE_NAME:$GITHUB_RUN_NUMBER
